services:
  - type: web
    name: helena-beach-resort
    runtime: image
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://helena.labcoop.online
      - key: SESSION_DOMAIN
        value: .helena.labcoop.online
      - key: APP_KEY
        value: base64:oSSlyK8+E6NGVJ3tFKw+9W0YiyK+j6gyqn4k0r0OeKs=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: helena-beach-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: helena-beach-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: helena-beach-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: helena-beach-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: FILESYSTEM_DISK
        value: cloudflare
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        sync: false
      - key: CLOUDFLARE_R2_URL
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
