<?php

namespace Tests\Feature;

use App\Models\Cottage;
use App\Models\Inquiry;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class Phase6QuickWinsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    public function test_sitemap_all_static_entries_have_lastmod(): void
    {
        $response = $this->get('/sitemap.xml');
        $content = $response->getContent();

        // Count <url> entries
        preg_match_all('/<url>/', $content, $matches);
        $urlCount = count($matches[0]);
        $this->assertGreaterThan(5, $urlCount);

        // Every <url> must contain a <lastmod> tag
        preg_match_all('/<lastmod>/', $content, $lastmodMatches);
        $this->assertEquals($urlCount, count($lastmodMatches[0]), 'Every sitemap <url> should have a <lastmod>');
    }

    public function test_booking_lookup_has_noindex(): void
    {
        $this->get('/booking/lookup')
            ->assertStatus(200)
            ->assertSee('noindex, nofollow', false);
    }

    public function test_booking_detail_has_noindex(): void
    {
        $inquiry = Inquiry::where('status', 'confirmed')->first() ?? $this->createInquiry('confirmed');

        $this->withSession(['booking_access_tokens' => [$inquiry->id => $inquiry->token]])
            ->get("/booking/{$inquiry->id}")
            ->assertStatus(200)
            ->assertSee('noindex, nofollow', false);
    }

    public function test_confirmation_page_has_noindex(): void
    {
        $inquiry = Inquiry::first() ?? $this->createInquiry();

        $this->withSession(['booking_access_tokens' => [$inquiry->id => $inquiry->token]])
            ->get("/booking/confirmation/{$inquiry->id}")
            ->assertStatus(200)
            ->assertSee('noindex, nofollow', false);
    }

    public function test_home_page_does_not_have_noindex(): void
    {
        $this->get('/')
            ->assertStatus(200)
            ->assertDontSee('noindex', false);
    }

    public function test_paginate_works_via_base_controller(): void
    {
        // Gallery uses the inherited paginate() from the base Controller
        $response = $this->get('/gallery');
        $response->assertStatus(200);
    }

    public function test_news_paginate_works_via_base_controller(): void
    {
        $response = $this->get('/news');
        $response->assertStatus(200);
    }

    /**
     * Self-contained inquiry for the noindex probes. The token and
     * reference code are auto-generated by the model on creating.
     */
    private function createInquiry(string $status = 'pending'): Inquiry
    {
        return Inquiry::create([
            'name' => 'SEO Guest',
            'email' => 'seo@example.com',
            'phone' => '09170000000',
            'check_in' => '2026-10-01',
            'check_out' => '2026-10-03',
            'cottage_id' => Cottage::first()->id,
            'pax' => 2,
            'booking_type' => 'overnight',
            'status' => $status,
            'source' => 'website',
        ]);
    }
}
